vsphere_server = "server.domain.local"
vsphere_user = "administrator@vsphere.local"
vsphere_password = "password"
vsphere_template_name = "ubuntu2404-testtemplate"
vsphere_folder = "Templates"
vsphere_dc_name = "DC name"
cluster = "clustername"
vsphere_host = "host.domain.local"
vsphere_portgroup_name = "DPG-Servers"
vsphere_datastore = "datastore1"
cpu_num = 4
mem_size = 4096
disk_size = 102400
vm_disk_controller_type = ["pvscsi"]